server:
  port: 8081
spring:
    mvc:
      view:
        prefix: /WEB-INF/views/
        suffix: .jsp
    servlet:
      multipart:
        max-file-size: 500MB
        max-request-size: 500MB
#  设置单个文件大小
#  spring.servlet.multipart.max-file-size= 50MB
#  设置单次请求文件的总大小
#  spring.servlet.multipart.max-request-size= 50MB